backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Blog Articles"
    folder: "src/content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Author", name: "author", widget: "string", default: "Dr. Roitman"}
      - {label: "Publish Date", name: "publishedAt", widget: "datetime"}
      - {label: "Reading Time (minutes)", name: "readingTime", widget: "number", default: 5}
      - {label: "Category", name: "category", widget: "select", options: ["Clinical Cases", "Clinical Techniques", "Technology", "Patient Education", "Practice Management"]}
      - {label: "Tags", name: "tags", widget: "list", default: ["Endodontics"]}
      - {label: "Status", name: "status", widget: "select", options: ["draft", "published"], default: "draft"}
      - {label: "Body", name: "body", widget: "markdown"}